slam_toolbox:
  ros__parameters:
    mode: mapping
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    resolution: 0.05
    transform_publish_period: 0.05
    use_scan_matching: true
    # map_file_name: "/home/dliujm/maps/ranger_map"
    map_start_pose: [0.0, 0.0, 0.0]